[tool.poetry]
name = "repl_python3_beta_nq-cli"
version = "0.1.0"
description = ""
authors = ["AXOME <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
